Add a little error handling, ignore missing files

diff --git a/src/bin/sync-removed-watch b/src/bin/sync-removed-watch
--- a/src/bin/sync-removed-watch
+++ b/src/bin/sync-removed-watch
@@ -16,6 +16,17 @@ watch_removed() {
             user_id="$(extract_user_id_from_path "$removed_path")"
             path="$(extract_relative_path "$removed_path")"
             asset_id="$(get_asset_by_path_from_db "$user_id" "$path")"
+
+            if [ -z "$asset_id" ]; then
+                echo "ERROR: Asset not found in database (user $user_id, path $path)"
+                continue
+            fi
+
+            if ! immich_api "$KEY" "/asset/assetById/$asset_id" | jq -e .id > /dev/null; then
+                echo "Asset $asset_id not found in Immich (user $user_id, path $path)"
+                continue
+            fi
+
             status="$(immich_delete_asset "$KEY" "$asset_id" | jq -r .[].status)"
             if [ "x$status" == "xSUCCESS" ]; then
                 echo "Asset $asset_id removed from Immich (user $user_id, path $path)"
