Working daily import service

diff --git a/src/bin/sync-import-watch b/src/bin/sync-import-watch
--- a/src/bin/sync-import-watch
+++ b/src/bin/sync-import-watch
@@ -6,7 +6,12 @@ else
     . $SNAP/bin/sync
 fi
 
-if ! immich_server_ready; then
+if [ -z $SNAP ]; then
+    echo "Abort: Only run this inside the snap"
+    exit 0
+fi
+
+if ! sync_enabled; then
     echo "Folder sync disabled"
     exit 0
 fi
@@ -16,12 +21,11 @@ block_immich_server_ready
 for KEY in $(get_keys); do
     USER_ID="$(user_id $KEY)"
 
-    if [ -z "$USER_ID" ]; then
+    if [ ! -z "$USER_ID" ]; then
         USER_PATH="$SNAP_COMMON/sync/$USER_ID"
         mkdir -p "$USER_PATH"
 
-        if [ ! -z $SNAP ]; then
-            $SNAP/bin/immich-cli upload --key "$KEY" --yes --recursive "$USER_PATH"
-        fi
+        echo "Full import of $USER_PATH for user $USER_ID"
+        upload "$KEY" --recursive "$USER_PATH"
     fi
 done
