Move functions closer to logic

diff --git a/src/bin/sync-removed-watch b/src/bin/sync-removed-watch
--- a/src/bin/sync-removed-watch
+++ b/src/bin/sync-removed-watch
@@ -9,6 +9,23 @@ fi
 block_sync_enabled
 block_immich_server_ready
 
+
+watch_removed() {
+    cat - | while read -r removed_path; do
+        if ! ignore_path "$removed_path"; then
+            user_id="$(extract_user_id_from_path "$removed_path")"
+            path="$(extract_relative_path "$removed_path")"
+            asset_id="$(get_asset_by_path_from_db "$user_id" "$path")"
+            status="$(immich_delete_asset "$KEY" "$asset_id" | jq -r .[].status)"
+            if [ "x$status" == "xSUCCESS" ]; then
+                echo "Asset $asset_id removed from Immich (user $user_id, path $path)"
+            else
+                echo "ERROR: Asset $asset_id not removed from Immich (user $user_id, path $path)"
+            fi
+        fi
+    done
+}
+
 for KEY in $(get_keys); do
     USER_ID="$(user_id $KEY)"
 
