Manually install sharp with a lot of checks
I'm not sure _why_ this fixes it. I do not sure that craftctl changes
anything relevant here, and I install exactly the same version of sharp
that the "npm ci" did ...

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -185,17 +185,41 @@ parts:
     source: https://github.com/immich-app/immich.git
     source-tag: v1.101.0
     override-build: |
+      craftctl default
+
       cd server
 
+      SHARP_VERSION=0.33.0
+
+      if [[ "$(node -p "require('./package.json').dependencies.sharp")" == "^$SHARP_VERSION" ]]; then
+        echo "Sharp version is correct"
+      else
+        echo "Sharp version is incorrect"
+        exit 1
+      fi
+
       # needed for sharp to build from source
-      npm install --save-dev node-addon-api node-gyp
+      npm install --save node-addon-api node-gyp
+      npm install --save sharp@$SHARP_VERSION
+
+      # Verify that sharp thinks it should use the global libvips
+      (
+        cd node_modules/sharp/src
+        if [[ "$(node -p "Boolean(require('../lib/libvips').useGlobalLibvips()).toString()")" != "true" ]]; then
+          echo "Error Sharp useGlobalLibvips returned false. Global libvips is not used."
+          exit 1
+        fi
+      )
 
       npm ci
       npm run build
       npm prune --omit=dev --omit=optional
 
-      # Verify that sharp was built from source
-      test -e node_modules/sharp/src/build/Release/sharp-linux-x64.node
+      # Verify that sharp was built from source, and that the binary is still present (after ci & prune)
+      if [[ ! -e node_modules/sharp/src/build/Release/sharp-linux-x64.node ]]; then
+        echo "Sharp was not built from source, missing sharp-linux-x64.node"
+        exit 1
+      fi
 
       mkdir -p ${CRAFT_PART_INSTALL}/usr/src/app
       cp -r node_modules ${CRAFT_PART_INSTALL}/usr/src/app
